"""Added Tables for Stripe

Revision ID: 0d67de567f54
Revises: 6f3f0b154258
Create Date: 2018-07-04 13:19:30.553003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d67de567f54'
down_revision = '6f3f0b154258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StripeCustomers',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.add_column('HotelBooking', sa.Column('IsPaid', sa.Boolean(), nullable=True))
    op.add_column('TicketBooking', sa.Column('IsPaid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TicketBooking', 'IsPaid')
    op.drop_column('HotelBooking', 'IsPaid')
    op.drop_table('StripeCustomers')
    # ### end Alembic commands ###
