"""Added Tickets Model

Revision ID: 0fa961b089a7
Revises: 1d6edb4dc0b7
Create Date: 2018-06-23 17:19:13.599616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa961b089a7'
down_revision = '1d6edb4dc0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tickets',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Origin', sa.String(length=100), nullable=True),
    sa.Column('Arrival', sa.String(length=100), nullable=True),
    sa.Column('DepartureDate', sa.Date(), nullable=True),
    sa.Column('ReturnDate', sa.Date(), nullable=True),
    sa.Column('IsPackaged', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tickets')
    # ### end Alembic commands ###
