"""Added Roles and Active to User

Revision ID: 1d6edb4dc0b7
Revises: c66fc12680e0
Create Date: 2018-06-23 14:43:33.261117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6edb4dc0b7'
down_revision = 'c66fc12680e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('Email', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'Email')
    # ### end Alembic commands ###
