"""New Field for Hotel

Revision ID: 2933b661a9d9
Revises: eec1ff278bd7
Create Date: 2018-07-01 01:04:27.782727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2933b661a9d9'
down_revision = 'eec1ff278bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Hotels', sa.Column('Price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Hotels', 'Price')
    # ### end Alembic commands ###
