"""empty message

Revision ID: 2ff5052ad505
Revises: 243d46491db2
Create Date: 2018-07-05 15:56:00.660454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff5052ad505'
down_revision = '243d46491db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Packages', sa.Column('Note', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Packages', 'Note')
    # ### end Alembic commands ###
