"""Added Expiration and Slots in Tickets Model

Revision ID: 3d36e928ddb8
Revises: 497f46d9dfc8
Create Date: 2018-06-23 17:34:08.345365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d36e928ddb8'
down_revision = '497f46d9dfc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tickets', sa.Column('IsExpired', sa.Boolean(), nullable=True))
    op.add_column('Tickets', sa.Column('RemainingSlots', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tickets', 'RemainingSlots')
    op.drop_column('Tickets', 'IsExpired')
    # ### end Alembic commands ###
