"""Added price

Revision ID: 3e3766f831b8
Revises: 5a06042fad8b
Create Date: 2018-06-30 22:54:14.876922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3766f831b8'
down_revision = '5a06042fad8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HotelInquiry',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=True),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('Location', sa.String(length=100), nullable=True),
    sa.Column('Budget', sa.Integer(), nullable=True),
    sa.Column('Guest', sa.Integer(), nullable=True),
    sa.Column('checkInDate', sa.Date(), nullable=True),
    sa.Column('checkOutDate', sa.Date(), nullable=True),
    sa.Column('Note', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.add_column('Tickets', sa.Column('Price', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('ContactNumber', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('Email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'Email')
    op.drop_column('customer', 'ContactNumber')
    op.drop_column('Tickets', 'Price')
    op.drop_table('HotelInquiry')
    # ### end Alembic commands ###
