"""Add LogTrail Model

Revision ID: 3f27858d6d2c
Revises: 85941e00b246
Create Date: 2018-06-24 17:56:26.916063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f27858d6d2c'
down_revision = '85941e00b246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_trail',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Event', sa.String(length=250), nullable=True),
    sa.Column('EventTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_trail')
    # ### end Alembic commands ###
