"""Added new fields to Tickets

Revision ID: 45712768de64
Revises: d40c09eb15d8
Create Date: 2018-07-02 17:35:08.802874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45712768de64'
down_revision = 'd40c09eb15d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Packages',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Destination', sa.String(length=50), nullable=True),
    sa.Column('Price', sa.Integer(), nullable=True),
    sa.Column('DaysOfStay', sa.Integer(), nullable=True),
    sa.Column('DepartureDate', sa.Date(), nullable=True),
    sa.Column('DepartureTime', sa.Time(), nullable=True),
    sa.Column('ReturnDate', sa.Date(), nullable=True),
    sa.Column('ReturnTime', sa.Time(), nullable=True),
    sa.Column('Intenerary', sa.String(length=1000), nullable=True),
    sa.Column('Inclusions', sa.String(length=1000), nullable=True),
    sa.Column('RemainingSlots', sa.Integer(), nullable=True),
    sa.Column('ExpirationDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('package')
    op.add_column('Tickets', sa.Column('ArrivalDate', sa.Date(), nullable=True))
    op.add_column('Tickets', sa.Column('ArrivalTime', sa.Time(), nullable=True))
    op.add_column('Tickets', sa.Column('FlightNo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tickets', 'FlightNo')
    op.drop_column('Tickets', 'ArrivalTime')
    op.drop_column('Tickets', 'ArrivalDate')
    op.create_table('package',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"package_Id_seq"\'::regclass)'), nullable=False),
    sa.Column('Destination', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DaysOfStay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DepartureDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('DepartureTime', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('ReturnDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ReturnTime', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('Intenerary', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('Inclusions', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('RemainingSlots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ExpirationDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='package_pkey')
    )
    op.drop_table('Packages')
    # ### end Alembic commands ###
