"""Added Time in Tickets Model

Revision ID: 497f46d9dfc8
Revises: 0fa961b089a7
Create Date: 2018-06-23 17:29:16.945728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497f46d9dfc8'
down_revision = '0fa961b089a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tickets', sa.Column('DepartureTime', sa.Time(), nullable=True))
    op.add_column('Tickets', sa.Column('ReturnTime', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tickets', 'ReturnTime')
    op.drop_column('Tickets', 'DepartureTime')
    # ### end Alembic commands ###
