"""Add LogTrail Model

Revision ID: 56ffc7f7ae94
Revises: 3f27858d6d2c
Create Date: 2018-06-24 18:00:19.612771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56ffc7f7ae94'
down_revision = '3f27858d6d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LogTrail',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Event', sa.String(length=250), nullable=True),
    sa.Column('EventTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('log_trail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_trail',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"log_trail_Id_seq"\'::regclass)'), nullable=False),
    sa.Column('Event', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('EventTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='log_trail_pkey')
    )
    op.drop_table('LogTrail')
    # ### end Alembic commands ###
