"""Added foreign keys

Revision ID: 5777a692da38
Revises: e389074b9037
Create Date: 2018-07-02 21:38:44.426933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5777a692da38'
down_revision = 'e389074b9037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Packages', sa.Column('hotelfk_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Packages', 'Hotels', ['hotelfk_id'], ['Id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Packages', type_='foreignkey')
    op.drop_column('Packages', 'hotelfk_id')
    # ### end Alembic commands ###
