"""Added InquireFlights

Revision ID: 5a06042fad8b
Revises: 4d61abdd8213
Create Date: 2018-06-30 17:54:51.100704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a06042fad8b'
down_revision = '4d61abdd8213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FlightInquiry',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=True),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('Origin', sa.String(length=100), nullable=True),
    sa.Column('Arrival', sa.String(length=100), nullable=True),
    sa.Column('DepartureDate', sa.Date(), nullable=True),
    sa.Column('ArrivalDate', sa.Date(), nullable=True),
    sa.Column('DesiredTime', sa.String(length=100), nullable=True),
    sa.Column('NumberOfAdults', sa.Integer(), nullable=True),
    sa.Column('NumberOfChild', sa.Integer(), nullable=True),
    sa.Column('NumberOfInfant', sa.Integer(), nullable=True),
    sa.Column('Note', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FlightInquiry')
    # ### end Alembic commands ###
