"""Tables Init

Revision ID: 667690d34f0b
Revises: 
Create Date: 2018-06-17 23:34:47.728885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667690d34f0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Users',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=100), nullable=True),
    sa.Column('Password', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Roles')
    # ### end Alembic commands ###
