"""Added Date Created and Date Updated

Revision ID: 85941e00b246
Revises: f9d2823c4bb2
Create Date: 2018-06-23 21:49:07.993941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85941e00b246'
down_revision = 'f9d2823c4bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hotels',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=250), nullable=True),
    sa.Column('Room Type', sa.String(length=250), nullable=True),
    sa.Column('Capacity', sa.String(length=250), nullable=True),
    sa.Column('Details', sa.String(length=250), nullable=True),
    sa.Column('Days', sa.Integer(), nullable=True),
    sa.Column('Nights', sa.Integer(), nullable=True),
    sa.Column('ExpirationDate', sa.Date(), nullable=True),
    sa.Column('IsExpired', sa.Boolean(), nullable=True),
    sa.Column('isPackaged', sa.Boolean(), nullable=True),
    sa.Column('DateCreated', sa.DateTime(), nullable=True),
    sa.Column('DateUpdated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.add_column('Tickets', sa.Column('DateCreated', sa.DateTime(), nullable=True))
    op.add_column('Tickets', sa.Column('DateUpdated', sa.DateTime(), nullable=True))
    op.add_column('Users', sa.Column('DateCreated', sa.DateTime(), nullable=True))
    op.add_column('Users', sa.Column('DateUpdated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'DateUpdated')
    op.drop_column('Users', 'DateCreated')
    op.drop_column('Tickets', 'DateUpdated')
    op.drop_column('Tickets', 'DateCreated')
    op.drop_table('Hotels')
    # ### end Alembic commands ###
