"""Added New Fields

Revision ID: add6823ce123
Revises: 539d9c0b2a27
Create Date: 2018-07-04 13:43:06.172664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add6823ce123'
down_revision = '539d9c0b2a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Hotels', sa.Column('RemainingRooms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Hotels', 'RemainingRooms')
    # ### end Alembic commands ###
