"""Added new Fields and Tables

Revision ID: b6b6aa1d61d1
Revises: 
Create Date: 2018-07-03 23:19:30.462093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b6aa1d61d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FlightInquiry',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=True),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('Origin', sa.String(length=100), nullable=True),
    sa.Column('Arrival', sa.String(length=100), nullable=True),
    sa.Column('DepartureDate', sa.Date(), nullable=True),
    sa.Column('ArrivalDate', sa.Date(), nullable=True),
    sa.Column('DesiredTime', sa.String(length=100), nullable=True),
    sa.Column('NumberOfAdults', sa.Integer(), nullable=True),
    sa.Column('NumberOfChild', sa.Integer(), nullable=True),
    sa.Column('NumberOfInfant', sa.Integer(), nullable=True),
    sa.Column('Note', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('HotelInquiry',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=True),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('Location', sa.String(length=100), nullable=True),
    sa.Column('Budget', sa.Integer(), nullable=True),
    sa.Column('Guest', sa.Integer(), nullable=True),
    sa.Column('checkInDate', sa.Date(), nullable=True),
    sa.Column('checkOutDate', sa.Date(), nullable=True),
    sa.Column('Note', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Hotels',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=250), nullable=True),
    sa.Column('Room Type', sa.String(length=250), nullable=True),
    sa.Column('Capacity', sa.String(length=4), nullable=True),
    sa.Column('Details', sa.String(length=300), nullable=True),
    sa.Column('CheckIn', sa.DateTime(), nullable=True),
    sa.Column('CheckOut', sa.DateTime(), nullable=True),
    sa.Column('Price', sa.Float(asdecimal=True), nullable=True),
    sa.Column('ExpirationDate', sa.Date(), nullable=True),
    sa.Column('IsExpired', sa.Boolean(), nullable=True),
    sa.Column('isPackaged', sa.Boolean(), nullable=True),
    sa.Column('DateCreated', sa.DateTime(), nullable=True),
    sa.Column('DateUpdated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('LogTrail',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Event', sa.String(length=250), nullable=True),
    sa.Column('EventTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Tickets',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FlightNo', sa.String(length=100), nullable=True),
    sa.Column('Origin', sa.String(length=100), nullable=True),
    sa.Column('Arrival', sa.String(length=100), nullable=True),
    sa.Column('DepartureDate', sa.Date(), nullable=True),
    sa.Column('DepartureTime', sa.Time(), nullable=True),
    sa.Column('ArrivalDate', sa.Date(), nullable=True),
    sa.Column('ArrivalTime', sa.Time(), nullable=True),
    sa.Column('ReturnDate', sa.Date(), nullable=True),
    sa.Column('ReturnTime', sa.Time(), nullable=True),
    sa.Column('RemainingSlots', sa.Integer(), nullable=True),
    sa.Column('ExpirationDate', sa.Date(), nullable=True),
    sa.Column('Price', sa.Float(asdecimal=True), nullable=True),
    sa.Column('IsExpired', sa.Boolean(), nullable=True),
    sa.Column('IsPackaged', sa.Boolean(), nullable=True),
    sa.Column('DateCreated', sa.DateTime(), nullable=True),
    sa.Column('DateUpdated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Users',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=100), nullable=True),
    sa.Column('Password', sa.String(length=250), nullable=True),
    sa.Column('Email', sa.String(length=250), nullable=True),
    sa.Column('FirstName', sa.String(length=250), nullable=True),
    sa.Column('LastName', sa.String(length=250), nullable=True),
    sa.Column('Role', sa.String(length=100), nullable=True),
    sa.Column('DateCreated', sa.DateTime(), nullable=True),
    sa.Column('DateUpdated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('customer',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=250), nullable=True),
    sa.Column('LastName', sa.String(length=250), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('ContactNumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Packages',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Destination', sa.String(length=50), nullable=True),
    sa.Column('Price', sa.Float(asdecimal=True), nullable=True),
    sa.Column('DaysOfStay', sa.Integer(), nullable=True),
    sa.Column('Intenerary', sa.String(length=1000), nullable=True),
    sa.Column('Inclusions', sa.String(length=1000), nullable=True),
    sa.Column('RemainingSlots', sa.Integer(), nullable=True),
    sa.Column('ExpirationDate', sa.Date(), nullable=True),
    sa.Column('HotelsFk', sa.Integer(), nullable=True),
    sa.Column('FlightFk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FlightFk'], ['Tickets.Id'], ),
    sa.ForeignKeyConstraint(['HotelsFk'], ['Hotels.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Packages')
    op.drop_table('customer')
    op.drop_table('Users')
    op.drop_table('Tickets')
    op.drop_table('LogTrail')
    op.drop_table('Hotels')
    op.drop_table('HotelInquiry')
    op.drop_table('FlightInquiry')
    # ### end Alembic commands ###
