"""New Relationship

Revision ID: bc3cb371202d
Revises: 2ff5052ad505
Create Date: 2018-07-05 18:19:18.045182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3cb371202d'
down_revision = '2ff5052ad505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PackageBooking',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('ReferenceNumber', sa.String(length=50), nullable=True),
    sa.Column('CustomersFk', sa.Integer(), nullable=True),
    sa.Column('PackagesFk', sa.Integer(), nullable=True),
    sa.Column('IsPaid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['CustomersFk'], ['Customers.Id'], ),
    sa.ForeignKeyConstraint(['PackagesFk'], ['Packages.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PackageBooking')
    # ### end Alembic commands ###
