"""Added new field for User

Revision ID: c66fc12680e0
Revises: 667690d34f0b
Create Date: 2018-06-18 00:41:34.642708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66fc12680e0'
down_revision = '667690d34f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Roles')
    op.add_column('Users', sa.Column('FirstName', sa.String(length=250), nullable=True))
    op.add_column('Users', sa.Column('LastName', sa.String(length=250), nullable=True))
    op.add_column('Users', sa.Column('Role', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'Role')
    op.drop_column('Users', 'LastName')
    op.drop_column('Users', 'FirstName')
    op.create_table('Roles',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"Roles_Id_seq"\'::regclass)'), nullable=False),
    sa.Column('Name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='Roles_pkey')
    )
    # ### end Alembic commands ###
