"""Added foreign keys

Revision ID: e389074b9037
Revises: 45712768de64
Create Date: 2018-07-02 21:31:41.433496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e389074b9037'
down_revision = '45712768de64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Packages', 'ReturnDate')
    op.drop_column('Packages', 'DepartureTime')
    op.drop_column('Packages', 'DepartureDate')
    op.drop_column('Packages', 'ReturnTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Packages', sa.Column('ReturnTime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('Packages', sa.Column('DepartureDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('Packages', sa.Column('DepartureTime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('Packages', sa.Column('ReturnDate', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
