"""Changed Table name of Customers

Revision ID: e3dba81d126c
Revises: b6b6aa1d61d1
Create Date: 2018-07-03 23:20:09.883805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3dba81d126c'
down_revision = 'b6b6aa1d61d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customers',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=250), nullable=True),
    sa.Column('LastName', sa.String(length=250), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('ContactNumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"customer_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('FirstName', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('LastName', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('Email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ContactNumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='customer_pkey')
    )
    op.drop_table('Customers')
    # ### end Alembic commands ###
