"""Upgrading data

Revision ID: eec1ff278bd7
Revises: 3e3766f831b8
Create Date: 2018-07-01 00:34:03.725311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec1ff278bd7'
down_revision = '3e3766f831b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Hotels', sa.Column('CheckIn', sa.DateTime(), nullable=True))
    op.add_column('Hotels', sa.Column('CheckOut', sa.DateTime(), nullable=True))
    op.drop_column('Hotels', 'Days')
    op.drop_column('Hotels', 'Nights')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Hotels', sa.Column('Nights', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Hotels', sa.Column('Days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Hotels', 'CheckOut')
    op.drop_column('Hotels', 'CheckIn')
    # ### end Alembic commands ###
