"""Added Expiration Date to Tickets

Revision ID: f9d2823c4bb2
Revises: 3d36e928ddb8
Create Date: 2018-06-23 19:30:18.401799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d2823c4bb2'
down_revision = '3d36e928ddb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tickets', sa.Column('ExpirationDate', sa.Date(), nullable=True))
    op.alter_column('Tickets', 'RemainingSlots',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tickets', 'RemainingSlots',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Tickets', 'ExpirationDate')
    # ### end Alembic commands ###
